version: "3"
services: 
    seanayepi:
        image: seanayepi:latest
        build:
            context: './'
        ports:
            - '5000:5000'

    mongo:
        image: mongo
        ports: 
            - '27017:27017'
        volumes: 
            - mongo:/data/db

volumes: 
    mongo:
        driver: local